
all : debug

debug :
	cd Framework; make debug; cd -
	cd FrameworkTest; make debug; cd -
	cd MockClientChannel; make debug; cd -

release :
	cd Framework; make release; cd -
	cd FrameworkTest; make release; cd -
	cd MockClientChannel; make release; cd -

clean:
	cd Framework; make clean; cd -
	cd FrameworkTest; make clean; cd -
	cd MockClientChannel; make clean; cd -
